<script src="<?php echo $this->config->base_url(); ?>assets/js/jquery.js"></script><script src="<?php echo $this->config->base_url(); ?>assets/js/jquery-ui-1.9.2.custom.min.js"></script><script type="text/javascript" src="<?php echo $this->config->base_url(); ?>assets/bootstrap/js/bootstrap.min.js"></script><script src="<?php echo $this->config->base_url(); ?>assets/js/bootstrap-editable.min.js"></script><script src="<?php echo $this->config->base_url(); ?>assets/js/moment-with-locales.min.js"></script>		<script src="<?php echo $this->config->base_url(); ?>assets/js/carregamento.js"></script>		<?php $base = base_url();?><script type="text/javascript">	$(document).ready(function(){	<?php include("carregamento.js")?>		$( "#estado" ).change(function() {			var estado = $('#estado').val();				$.getJSON('<?php echo $this->config->base_url();?>index.php/estado/listarCidadesComCnpj?estado='+estado, function (dados){				 			   if (dados.length > 0){    				  var option = '<option  value=0>Selecione a cidade</option>';				  $.each(dados, function(i, obj){					  option += '<option value="'+obj.id+'">'+obj.nome+'</option>';				  })				  $('#cidade').html(option).show();			   }else{				   Reset();				   option = '<option>Não foram encontradas cidades!</option>';				   $('#cidade').html(option).show();			   }			})	});
	$( "#cidade" ).change(function() {			var estado = $('#estado').val();			var cidade = $('#cidade').val();			$.getJSON('<?php echo $this->config->base_url();?>index.php/cnpj/listarCnpjFilhosJson?cnpjRaiz=0&estado='+estado+'&cidade='+cidade, function (dados){				 			   if (dados.length > 0){    				  var option = '<option  value=0>Selecione o cnpj </option>';				  $.each(dados, function(i, obj){					  option += '<option value="'+obj.id+'">'+obj.cnpj+'</option>';				  })				  $('#cnpj').html(option).show();			   }else{				   Reset();				   option = '<option>Não foram encontrados cnpjs!</option>';				   $('#cnpj').html(option).show();			   }			})	});
});		
</script>		<div id="wrapper">                <div class="content-wrapper container">                    <div class="row">                        <div class="col-sm-12">                            <div class="page-title">                                <h1>Ocorr&ecirc;ncias <small>	</small></h1>                                <ol class="breadcrumb">                                                                        <li class="active">Lista de Ocorr&ecirc;ncias </li>                                </ol>                            </div>                        </div>                    </div><!-- end .page title-->                    <div class="row">                        <div class="col-md-12">                            <div class="panel panel-card ">                                <!-- Start .panel -->                                <div class="panel-heading">                                    <h4 class="panel-title"> 									<?php if($_SESSION['login_tejofran_protesto']['consulta'] ==0 ){?>										<a href="<?php echo $this->config->base_url();?>index.php/protesto/cadastrar"> <i class="fa fa-plus" aria-hidden="true"></i>&nbsp;Nova Ocorr&ecirc;ncia</a> 									<?php }?>																		</h4>									<br>																		<?php include("opcoes_ocorrencias_view.php")?>									
									&nbsp;													                                    <div class="panel-actions">
                                        <a href="#" class="panel-action panel-action-toggle" data-panel-toggle></a>
                                        <a href="#" class="panel-action panel-action-dismiss" data-panel-dismiss></a>
                                    </div>
                                </div>
                                       </div><!-- End .panel -->  
                        </div><!--end .col-->
                    </div><!--end .row-->                </div> 
            </div>